<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="UnitTests\Commands\" />
    <Folder Include="UnitTests\Handlers\" />
    <Folder Include="UnitTests\Queries\" />
  </ItemGroup>

</Project>
